// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Stock741.Data;

#nullable disable

namespace Stock741.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518132752_AddDatePretAndEdsAutomatiqueAffectation")]
    partial class AddDatePretAndEdsAutomatiqueAffectation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Stock741.Models.Affectation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("AdresseIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AncienPC")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePret")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EdsAutomatiqueId")
                        .HasColumnType("int");

                    b.Property<int?>("EdsId")
                        .HasColumnType("int");

                    b.Property<string>("EdsPC")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("ForfaitId")
                        .HasColumnType("int");

                    b.Property<string>("MasqueIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomAppareil")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomPC")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("NumTelMobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("OperateurId")
                        .HasColumnType("int");

                    b.Property<string>("PasserelleIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EdsAutomatiqueId");

                    b.HasIndex("EdsId");

                    b.HasIndex("ForfaitId");

                    b.HasIndex("OperateurId");

                    b.HasIndex("StockId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Affectations");
                });

            modelBuilder.Entity("Stock741.Models.Eds", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Adr1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adr2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adr3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adr4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnx")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Geolocalisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorJeudi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorLundi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorMardi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorMercredi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorSamedi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HorVendredi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MailContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Cnx")
                        .IsUnique();

                    b.ToTable("Eds", (string)null);
                });

            modelBuilder.Entity("Stock741.Models.EdsLiaison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cible")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EdsId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("EdsId");

                    b.ToTable("EdsLiaisons");
                });

            modelBuilder.Entity("Stock741.Models.Fiche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Fiches");
                });

            modelBuilder.Entity("Stock741.Models.Forfait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OperateurId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.HasIndex("OperateurId");

                    b.ToTable("Forfaits");
                });

            modelBuilder.Entity("Stock741.Models.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("Stock741.Models.HistoriqueMouvement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AffectationId")
                        .HasColumnType("int");

                    b.Property<string>("AncienAdresseIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AncienEdsId")
                        .HasColumnType("int");

                    b.Property<int?>("AncienLieuId")
                        .HasColumnType("int");

                    b.Property<string>("AncienMasqueIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AncienNomAppareil")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AncienNomPC")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<int?>("AncienStatutId")
                        .HasColumnType("int");

                    b.Property<int?>("AncienUtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("AnciennePasserelle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("datetime2");

                    b.Property<string>("EffectuePar")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NouveauLieuId")
                        .HasColumnType("int");

                    b.Property<int?>("NouveauStatutId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<string>("TypeMouvement")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AffectationId");

                    b.HasIndex("AncienEdsId");

                    b.HasIndex("AncienLieuId");

                    b.HasIndex("AncienStatutId");

                    b.HasIndex("AncienUtilisateurId");

                    b.HasIndex("NouveauLieuId");

                    b.HasIndex("NouveauStatutId");

                    b.HasIndex("StockId");

                    b.ToTable("HistoriqueMouvements");
                });

            modelBuilder.Entity("Stock741.Models.Lieu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Lieux");
                });

            modelBuilder.Entity("Stock741.Models.Marque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("Stock741.Models.Materiel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("FicheId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("FicheId");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Materiels");
                });

            modelBuilder.Entity("Stock741.Models.Modele", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("CheminPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<int>("MaterielId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("MarqueId");

                    b.HasIndex("MaterielId");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("Stock741.Models.Operateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Operateurs");
                });

            modelBuilder.Entity("Stock741.Models.Statut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Statuts");
                });

            modelBuilder.Entity("Stock741.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Asset")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Colis")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("0");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FournisseurId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Garantie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imei1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Imei2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LieuId")
                        .HasColumnType("int");

                    b.Property<int>("ModeleId")
                        .HasColumnType("int");

                    b.Property<string>("NumReception")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)")
                        .HasDefaultValue("0");

                    b.Property<string>("NumSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumSim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Qte")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("SousGarantie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("StatutId")
                        .HasColumnType("int");

                    b.Property<int?>("SystemeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Asset")
                        .IsUnique()
                        .HasFilter("[Asset] IS NOT NULL");

                    b.HasIndex("FournisseurId");

                    b.HasIndex("LieuId");

                    b.HasIndex("ModeleId");

                    b.HasIndex("StatutId");

                    b.HasIndex("SystemeId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("Stock741.Models.Systeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Systemes");
                });

            modelBuilder.Entity("Stock741.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Actif")
                        .HasColumnType("bit");

                    b.Property<string>("Bureau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodePays")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CreePar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateMiseAJour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FuseauHoraire")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdUtilisateur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdWindows")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MisAJourPar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Rue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Societe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TelephoneMobile")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelephoneProfessionnel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Vip")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdWindows")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Stock741.Models.Affectation", b =>
                {
                    b.HasOne("Stock741.Models.Eds", "EdsAutomatique")
                        .WithMany()
                        .HasForeignKey("EdsAutomatiqueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Eds", "Eds")
                        .WithMany()
                        .HasForeignKey("EdsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Forfait", "Forfait")
                        .WithMany()
                        .HasForeignKey("ForfaitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Operateur", "Operateur")
                        .WithMany()
                        .HasForeignKey("OperateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stock741.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Eds");

                    b.Navigation("EdsAutomatique");

                    b.Navigation("Forfait");

                    b.Navigation("Operateur");

                    b.Navigation("Stock");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Stock741.Models.EdsLiaison", b =>
                {
                    b.HasOne("Stock741.Models.Eds", "Eds")
                        .WithMany()
                        .HasForeignKey("EdsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Eds");
                });

            modelBuilder.Entity("Stock741.Models.Forfait", b =>
                {
                    b.HasOne("Stock741.Models.Operateur", "Operateur")
                        .WithMany()
                        .HasForeignKey("OperateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operateur");
                });

            modelBuilder.Entity("Stock741.Models.HistoriqueMouvement", b =>
                {
                    b.HasOne("Stock741.Models.Affectation", "Affectation")
                        .WithMany()
                        .HasForeignKey("AffectationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Eds", "AncienEds")
                        .WithMany()
                        .HasForeignKey("AncienEdsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Lieu", "AncienLieu")
                        .WithMany()
                        .HasForeignKey("AncienLieuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Statut", "AncienStatut")
                        .WithMany()
                        .HasForeignKey("AncienStatutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Utilisateur", "AncienUtilisateur")
                        .WithMany()
                        .HasForeignKey("AncienUtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Lieu", "NouveauLieu")
                        .WithMany()
                        .HasForeignKey("NouveauLieuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Statut", "NouveauStatut")
                        .WithMany()
                        .HasForeignKey("NouveauStatutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Affectation");

                    b.Navigation("AncienEds");

                    b.Navigation("AncienLieu");

                    b.Navigation("AncienStatut");

                    b.Navigation("AncienUtilisateur");

                    b.Navigation("NouveauLieu");

                    b.Navigation("NouveauStatut");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Stock741.Models.Materiel", b =>
                {
                    b.HasOne("Stock741.Models.Fiche", "Fiche")
                        .WithMany()
                        .HasForeignKey("FicheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fiche");
                });

            modelBuilder.Entity("Stock741.Models.Modele", b =>
                {
                    b.HasOne("Stock741.Models.Marque", "Marque")
                        .WithMany()
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stock741.Models.Materiel", "Materiel")
                        .WithMany()
                        .HasForeignKey("MaterielId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marque");

                    b.Navigation("Materiel");
                });

            modelBuilder.Entity("Stock741.Models.Stock", b =>
                {
                    b.HasOne("Stock741.Models.Fournisseur", "Fournisseur")
                        .WithMany()
                        .HasForeignKey("FournisseurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Lieu", "Lieu")
                        .WithMany()
                        .HasForeignKey("LieuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Modele", "Modele")
                        .WithMany()
                        .HasForeignKey("ModeleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Stock741.Models.Statut", "Statut")
                        .WithMany()
                        .HasForeignKey("StatutId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Stock741.Models.Systeme", "Systeme")
                        .WithMany()
                        .HasForeignKey("SystemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Fournisseur");

                    b.Navigation("Lieu");

                    b.Navigation("Modele");

                    b.Navigation("Statut");

                    b.Navigation("Systeme");
                });
#pragma warning restore 612, 618
        }
    }
}
