using System;
using System.Globalization;
using System.Linq;
using System.Windows.Controls;
using System.Windows.Data;

namespace Stock741.Views
{
    public partial class RequeteView : UserControl
    {
        public RequeteView()
        {
            InitializeComponent();
        }

        private void ResultatsDataGrid_AutoGeneratingColumn(object sender, DataGridAutoGeneratingColumnEventArgs e)
        {
            if (e.PropertyType == typeof(byte[]))
            {
                e.Column = new DataGridTextColumn
                {
                    Header = e.Column.Header,
                    Binding = new Binding(e.PropertyName)
                    {
                        Converter = new ByteArrayToHexConverter()
                    }
                };
                return;
            }

            if (e.PropertyType == typeof(DateTime) && e.Column is DataGridTextColumn textColumn)
            {
                textColumn.Binding = new Binding(e.PropertyName)
                {
                    StringFormat = "dd/MM/yyyy"
                };
            }
        }

        private void ResultatsDataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {
            if (sender is not DataGrid dataGrid)
                return;

            var rowVersionColumn = dataGrid.Columns.FirstOrDefault(c =>
                string.Equals(c.Header?.ToString(), "RowVersion", StringComparison.OrdinalIgnoreCase));

            if (rowVersionColumn != null)
                rowVersionColumn.DisplayIndex = dataGrid.Columns.Count - 1;
        }

        private sealed class ByteArrayToHexConverter : IValueConverter
        {
            public object Convert(object value, Type targetType, object parameter, CultureInfo culture)
            {
                return value is byte[] bytes
                    ? "0x" + BitConverter.ToString(bytes).Replace("-", string.Empty)
                    : string.Empty;
            }

            public object ConvertBack(object value, Type targetType, object parameter, CultureInfo culture)
                => throw new NotImplementedException();
        }
    }
}
